export interface Tour {
    id: string;
    title: string;
    duration: string;
    short_description: string;
    startDate: string;
    destinations: string[];
    price_adult: number;
    currency: string;
    fileWordUrl?: string;
    filePdfUrl?: string;
}

export const TOUR_LIST: Tour[] = [
    {
        id: "beijing-1",
        title: "Du lịch khám phá Bắc Kinh",
        duration: '5 ngày 4 đêm',
        startDate: '2/9/2025',
        short_description: "Tour Bắc Kinh khám phá trái tim văn hóa ngàn năm của Trung Hoa.",
        destinations: ["Bắc Kinh", "Macau", "Đà Nẵng"],
        price_adult: 16990000,
        currency: "VND",
        fileWordUrl: "/files/B2B_MONO_BACKINH_5ngay4dem.docx",
    },
    {
        id: "dubai-1",
        title: "Du lịch khám phá Dubai tháng 8",
        duration: '5 ngày 4 đêm',
        startDate: '2/9/2025',
        short_description: "Tour Dubai 5 ngày 4 đêm, trải nghiệm thành phố xa hoa và sa mạc.",
        destinations: ["Dubai", "Đà Nẵng"],
        price_adult: 25990000,
        currency: "VND",
        fileWordUrl: "/files/B2B_DUBAI_5D4N_EK_T682025.docx",
    },
    {
        id: "dubai-2",
        title: "Du lịch Dubai tháng 11",
        duration: '5 ngày 4 đêm',
        startDate: '2/9/2025',
        short_description: "Tour Dubai 5 ngày 4 đêm, khởi hành tháng 10/2025.",
        destinations: ["Dubai", "Đà Nẵng"],
        price_adult: 25990000,
        currency: "VND",
        fileWordUrl: "/files/B2B_DUBAI_5D4N_EK_T10112025.docx",
    },
    {
        id: "tay-an-1",
        title: "Du lịch khám phá Thanh Đô - Tây An",
        duration: '6 ngày 5 đêm',
        startDate: '2/9/2025',
        short_description: "Tour khám phá Thanh Đô - Tây An, di sản lịch sử Trung Hoa.",
        destinations: ["Thanh Đô", "Tây An", "Trung Quốc"],
        price_adult: 19990000,
        currency: "VND",
        fileWordUrl: "/files/B2B_NX_THANHDO_TAYAN_6ngay5dem.docx",
    },
    {
        id: "bk-th-1",
        title: "Du lịch khám phá Bắc Kinh - Thượng Hải tháng 8 ",
        duration: '8 ngày 7 đêm',
        startDate: '2/9/2025',
        short_description: "Tour Bắc Kinh - Thượng Hải 8 ngày 7 đêm, trải nghiệm đa sắc Trung Hoa.",
        destinations: ["Bắc Kinh", "Thượng Hải", "Trung Quốc"],
        price_adult: 23990000,
        currency: "VND",
        fileWordUrl: "/files/B2B_T82025_BK_TH_8ngay7dem.docx",
    },
    {
        id: "bk-th-2",
        title: "Du lịch khám phá Bắc Kinh - Thượng Hải tháng 9-12 ",
        duration: '8 ngày 7 đêm',
        startDate: '2/9/2025',
        short_description: "Tour Bắc Kinh - Thượng Hải 8 ngày 7 đêm, khởi hành tháng 9-12/2025.",
        destinations: ["Bắc Kinh", "Thượng Hải", "Trung Quốc"],
        price_adult: 23990000,
        currency: "VND",
        fileWordUrl: "/files/B2B_T9122025_BK_TH_8ngay7dem.docx",
    },
    {
        id: "korea-1",
        title: "Du lịch khám phá Hàn Quốc tháng 9",
        duration: '5 ngày 4 đêm',
        startDate: '2/9/2025',
        short_description: "Tour Hàn Quốc 5 ngày 4 đêm, trải nghiệm văn hóa và ẩm thực.",
        destinations: ["Hàn Quốc", "Seoul"],
        price_adult: 18990000,
        currency: "VND",
        fileWordUrl: "/files/B2B_VJ_KOREA_5D4N_01092025.docx",
    },
    {
        id: "japan-1",
        title: "Du lịch khám phá Nhật Bản",
        duration: '6 ngày 5 đêm',
        startDate: '2/9/2025',
        short_description: "Tour Nhật Bản 6 ngày 5 đêm, khám phá xứ sở hoa anh đào.",
        destinations: ["Nhật Bản", "Tokyo", "Osaka"],
        price_adult: 29990000,
        currency: "VND",
        fileWordUrl: "/files/B2B_VNA_JAPAN_2025_6ngay5dem.docx",
    },
    {
        id: "nhatban-1",
        title: "Du lịch khám phá Nhật Bản vào mùa thu",
        duration: '5 ngày 4 đêm',
        startDate: '2/9/2025',
        short_description: "Tour Nhật Bản mùa thu, trải nghiệm lá đỏ và văn hóa truyền thống.",
        destinations: ["Nhật Bản", "Đà Nẵng"],
        price_adult: 28990000,
        currency: "VND",
        fileWordUrl: "/files/DN_NHATBAN_CDV_MUATHU.docx",
    },
    {
        id: "nhatban-2",
        title: "Du lịch khám phá Nhật Bản tháng 7-10",
        duration: '5 ngày 4 đêm',
        startDate: '2/9/2025',
        short_description: "Tour Nhật Bản CDV khởi hành tháng 7-10, bay VNA.",
        destinations: ["Nhật Bản", "Đà Nẵng"],
        price_adult: 28990000,
        currency: "VND",
        fileWordUrl: "/files/DN_NHATBAN_CDV_THANG_7_10_VNA.docx",
    },
    {
        id: "thuonghai-1",
        title: "Du lịch khám Thượng Hải tháng 7-8",
        duration: '5 ngày 4 đêm',
        startDate: '2/9/2025',
        short_description: "Tour Thượng Hải 5 ngày 4 đêm, trải nghiệm thành phố hiện đại.",
        destinations: ["Thượng Hải", "Trung Quốc"],
        price_adult: 17990000,
        currency: "VND",
        fileWordUrl: "/files/T7_T82025_B2B_NX_THUONGHAI_5ngay4dem.docx",
    },
    {
        id: "thuonghai-2",
        title: "Du lịch khám phá THƯỢNG HẢI tháng 9",
        duration: '5 ngày 4 đêm',
        startDate: '2/9/2025',
        short_description: "Tour Thượng Hải 5 ngày 4 đêm, khởi hành tháng 9-12/2025.",
        destinations: ["Thượng Hải", "Trung Quốc"],
        price_adult: 17990000,
        currency: "VND",
        fileWordUrl: "/files/T9_T122025_B2B_NX_THUONGHAI_5ngay4dem.docx",
    },
    {
        id: "singapore-1",
        title: "Du lịch khám phá tháng 10-12 Đà Nẵng - Singapore - Malaysia",
        duration: '5 ngày 4 đêm',
        startDate: '2/9/2025',
        short_description: "Tour Đà Nẵng - Singapore - Malaysia 5 ngày 4 đêm, trải nghiệm Đông Nam Á.",
        destinations: ["Đà Nẵng", "Singapore", "Malaysia"],
        price_adult: 15990000,
        currency: "VND",
        fileWordUrl: "/files/THANG_10_12_DANANG_SINGAPORE_MALAYSIA_5N4D.docx",
    },
    {
        id: "hanquoc-1",
        title: "Du lịch khám phá tháng 9-12 Đà Nẵng - Hàn Quốc",
        duration: '5 ngày 4 đêm',
        startDate: '2/9/2025',
        short_description: "Tour Đà Nẵng - Hàn Quốc 5 ngày 4 đêm, mùa thu tuyệt đẹp.",
        destinations: ["Đà Nẵng", "Hàn Quốc"],
        price_adult: 18990000,
        currency: "VND",
        fileWordUrl: "/files/THANG_912_MUATHU_DANANG_HANQUOC_5N4D_2025.docx",
    },
    {
        id: "bangkok-1",
        title: "Du lịch khám phá tháng 8-12 Bangkok - Pattaya",
        duration: '5 ngày 4 đêm',
        startDate: '2/9/2025',
        short_description: "Tour Bangkok - Pattaya 5 ngày 4 đêm, khám phá Thái Lan sôi động.",
        destinations: ["Bangkok", "Pattaya", "Thái Lan"],
        price_adult: 12990000,
        currency: "VND",
        fileWordUrl: "/files/VZ_THANG_8_12_BANGKOK_PATTAYA_5N4D.docx",
    },
];
